services:
  web:
    build: ./fe
    image: "yanivomc/fe-exam:latest"
    ports:
      - "5002:5002"
    depends_on:
      - backend-service
    networks:
      - internal

  backend-service:
    build: ./be
    image: "yanivomc/be-exam:latest"
    networks:
      - internal
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456

  mysqldb:
      image: mysql:5.7
      networks:
        - internal
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        # create database name crypto_db
        MYSQL_DATABASE: crypto_db
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=123456"]
        interval: 30s
        retries: 3
        start_period: 2m   # 2 minute wait before health check starts
        timeout: 20s

networks:
  internal:
    driver: bridge


  