apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 5001
  type: {{ .Values.service.type }}