apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fe-be-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kobi070/devopshift-welcome.git'  # Replace with actual repo
    targetRevision: HEAD
    path: exam-code/k8s-manifests/argocd-fe-be.yaml  # Path to your YAML files
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fe-be-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true