pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub-credentials' // ID of the DockerHub credentials
        IMAGE_NAME = 'kobi070/demo-app:1.0'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building Docker image ${IMAGE_NAME}..."
                    // Ensure that Dockerfile and context directory are correct
                    docker.build(env.IMAGE_NAME, 'demos/jenkinsfiles/docker-jenkins/')
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    echo "Pushing Docker image to DockerHub..."
                    docker.withRegistry('https://index.docker.io/v1/', env.DOCKERHUB_CREDENTIALS) {
                        def appImage = docker.image(env.IMAGE_NAME)
                        appImage.push()
                    }
                }
            }
        }

        stage('Clean Up') {
            steps {
                // Use double quotes for variable substitution in shell commands
                sh "docker rmi ${IMAGE_NAME}"
            }
        }
    }

    post {
        always {
            echo "Pipeline completed."
        }
    }
}